#!/usr/bin/env python3
"""Regenerate m1ck4_pdfmd/ (a pinned copy of M1ck4/pdfmd, MIT) from upstream.

    vendor_m1ck4.py                    clone upstream at the pinned commit, apply
                                       scripts/m1ck4.patch, rewrite m1ck4_pdfmd/ and VENDORED.md
    vendor_m1ck4.py --upstream DIR     use an existing clone of upstream instead of cloning
    vendor_m1ck4.py --check            regenerate into a temp dir and fail if m1ck4_pdfmd/ differs
    vendor_m1ck4.py --update-patch     after editing m1ck4_pdfmd/ in place, rewrite
                                       scripts/m1ck4.patch as the diff from pristine upstream

m1ck4_pdfmd/ is generated: change it only through scripts/m1ck4.patch.
Upstream is archived, so the pin never moves unless someone decides it should.
"""
import argparse
import hashlib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
UPSTREAM_URL = "https://github.com/M1ck4/pdfmd"
UPSTREAM_COMMIT = "17b2cff1a952a3d6ae52820059eb09d662de71b0"
UPSTREAM_VERSION = "1.6.0"
DROPPED = {"app_gui.py"}          # Tk GUI, not used here
TARGET = REPO / "m1ck4_pdfmd"
PATCH = REPO / "scripts" / "m1ck4.patch"
NOTICE = REPO / "VENDORED.md"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def get_upstream(given: str | None, scratch: Path) -> Path:
    if given:
        root = Path(given).expanduser().resolve()
    else:
        root = scratch / "upstream"
        subprocess.run(["git", "clone", "-q", UPSTREAM_URL, str(root)], check=True)
    subprocess.run(["git", "-C", str(root), "checkout", "-q", UPSTREAM_COMMIT], check=True)
    head = subprocess.run(["git", "-C", str(root), "rev-parse", "HEAD"],
                          capture_output=True, text=True, check=True).stdout.strip()
    if head != UPSTREAM_COMMIT:
        sys.exit(f"upstream is at {head}, expected {UPSTREAM_COMMIT}")
    return root


def pristine_copy(upstream: Path, dest: Path) -> dict:
    dest.mkdir(parents=True)
    sums = {}
    for src in sorted((upstream / "pdfmd").glob("*.py")):
        if src.name in DROPPED:
            continue
        shutil.copy2(src, dest / src.name)
        sums[src.name] = sha256(src)
    shutil.copy2(upstream / "LICENSE", dest / "LICENSE")
    return sums


def apply_patch(tree: Path) -> None:
    if PATCH.exists() and PATCH.read_bytes().strip():
        subprocess.run(["patch", "-p1", "-s", "-d", str(tree), "-i", str(PATCH)], check=True)


def make_diff(pristine: Path, current: Path) -> bytes:
    out = []
    for a in sorted(pristine.glob("*.py")):
        b = current / a.name
        run = subprocess.run(["diff", "-u", "-L", f"a/{a.name}", "-L", f"b/{a.name}", str(a), str(b)],
                             capture_output=True)  # bytes: upstream files use CRLF line endings
        if run.returncode not in (0, 1):
            sys.exit(f"diff failed on {a.name}: {run.stderr.decode().strip()}")
        out.append(run.stdout)
    return b"".join(out)


def write_notice(sums: dict) -> None:
    rows = "\n".join(
        f"| `{n}` | `{h[:16]}` | `{sha256(TARGET / n)[:16]}` |" for n, h in sums.items())
    NOTICE.write_text(f"""# Vendored code

`m1ck4_pdfmd/` is a pinned copy of **pdfmd** by Michael Neivandt (M1ck4),
<{UPSTREAM_URL}>, MIT licence (`m1ck4_pdfmd/LICENSE`, copyright kept).
batchocr uses it for the PDF -> Markdown structure stages (heading, list, table
and math detection, Markdown rendering). It is not the PyPI package `pdfmd`
(an unrelated project) and not Ali's `pdfmd-cli`.

| | |
|---|---|
| upstream | {UPSTREAM_URL} |
| commit | `{UPSTREAM_COMMIT}` (v{UPSTREAM_VERSION}, repository archived) |
| dropped | `app_gui.py` (Tk GUI) |
| modifications | `scripts/m1ck4.patch` (sha256 `{sha256(PATCH)[:16]}`), applied on top of the pristine files |

`m1ck4_pdfmd/` is generated by `scripts/vendor_m1ck4.py`; do not edit it by hand.
To change it: edit the files in place, run `scripts/vendor_m1ck4.py --update-patch`,
commit the new patch. `--check` verifies the committed tree equals pristine + patch.

| file | pristine sha256 (first 16) | vendored sha256 (first 16) |
|---|---|---|
{rows}

PyMuPDF, which this code uses to read PDFs, is AGPL-3.0. It is not bundled; it
is an optional dependency installed separately (`pip install pymupdf`).
""")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--upstream")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--update-patch", action="store_true")
    args = ap.parse_args()
    with tempfile.TemporaryDirectory(prefix="vendor-m1ck4-") as td:
        scratch = Path(td)
        upstream = get_upstream(args.upstream, scratch)
        pristine = scratch / "pristine"
        sums = pristine_copy(upstream, pristine)
        if args.update_patch:
            PATCH.write_bytes(make_diff(pristine, TARGET))
            print(f"wrote {PATCH.relative_to(REPO)}")
        built = scratch / "built"
        shutil.copytree(pristine, built)
        apply_patch(built)
        if args.check:
            bad = [p.name for p in sorted(built.iterdir())
                   if not (TARGET / p.name).exists() or sha256(p) != sha256(TARGET / p.name)]
            extra = [p.name for p in TARGET.iterdir()
                     if p.is_file() and not (built / p.name).exists() and p.suffix != ".pyc"]
            if bad or extra:
                sys.exit(f"m1ck4_pdfmd/ differs from pristine + patch: {bad + extra}")
            print("m1ck4_pdfmd/ matches pristine upstream + scripts/m1ck4.patch")
            return
        shutil.rmtree(TARGET, ignore_errors=True)
        shutil.copytree(built, TARGET)
        write_notice(sums)
        print(f"wrote {TARGET.relative_to(REPO)}/ and {NOTICE.name}")


if __name__ == "__main__":
    main()
